const ADMIN_LOGIN='flareitvadm', ADMIN_PASSWORD='flareitvadm';
const DEFAULTS={liveEnabled:false,vkUrl:'',onairTitle:'FLARE. Новости',onairText:'Главные события дня — коротко и по делу.',nextTitle:'Истории города',nextTime:'10:25',newsSource:'telegram',newsTitle:'Главные события дня: что важно знать прямо сейчас',newsText:'Короткие новости, важные события и комментарии редакции FLARE.',newsTime:'СЕГОДНЯ · 10:15',news2Title:'Что изменится этой осенью',news2Text:'Главные изменения и события дня.',news2Category:'Общество',news3Title:'Новые технологии меняют привычный эфир',news3Text:'Главное из мира технологий.',news3Category:'Технологии',sch1Title:'FLARE. Новости',sch2Title:'Истории города',sch3Title:'Дайджест',sch4Title:'FLARE. Погода',aboutText:'FLARE — интернет-телеканал нового формата: новости, программы, прямые трансляции и важные события.',aboutYear:'2026',program1Title:'Дайджест',program1Text:'Самое важное за день',program2Title:'FLARE. Новости',program2Text:'Оперативно и без лишнего',program3Title:'Прямой эфир',program3Text:'События в реальном времени',rateUSD:92.5,rateEUR:107.8,rateGold:10450,rateSilver:145,ratePlatinum:4200,ratePalladium:3800,rateUpdated:''};
function getData(){try{return {...DEFAULTS,...JSON.parse(localStorage.getItem('flareData')||'{}')}}catch{return {...DEFAULTS}}}
function setVal(id,v){const e=document.getElementById(id);if(e)e.type==='checkbox'?e.checked=!!v:e.value=v??''}
function loadForm(){const d=getData();Object.entries(d).forEach(([k,v])=>setVal(k,v))}
function save(){const d={};Object.keys(DEFAULTS).forEach(k=>{const e=document.getElementById(k);if(e)d[k]=e.type==='checkbox'?e.checked:e.value});localStorage.setItem('flareData',JSON.stringify(d));document.getElementById('saved').textContent='Сохранено';setTimeout(()=>document.getElementById('saved').textContent='',1800)}
function showPanel(){document.getElementById('loginBox').hidden=true;document.getElementById('panel').hidden=false;loadForm()}
function setupTabs(){document.querySelectorAll('.adminTab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.adminTab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.adminTabPanel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab)?.classList.add('active')}))}
async function refreshRates(){const status=document.getElementById('rateStatus');status.textContent='Обновляем…';try{const r=await fetch('https://www.cbr-xml-daily.ru/daily_json.js',{cache:'no-store'});if(!r.ok)throw new Error('network');const j=await r.json();if(j.Valute?.USD?.Value)setVal('rateUSD',Number(j.Valute.USD.Value).toFixed(4));if(j.Valute?.EUR?.Value)setVal('rateEUR',Number(j.Valute.EUR.Value).toFixed(4));status.textContent='USD/EUR обновлены из ЦБ РФ';}catch(e){status.textContent='Не удалось обновить валюты. Введите значения вручную.'}setTimeout(()=>status.textContent='',3500)}
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const l=document.getElementById('login').value,p=document.getElementById('password').value;if(l===ADMIN_LOGIN&&p===ADMIN_PASSWORD){sessionStorage.setItem('flareAdmin','1');showPanel()}else document.getElementById('loginError').textContent='Неверный логин или пароль.'});
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('flareAdmin');location.reload()};document.getElementById('save').onclick=save;document.getElementById('reset').onclick=()=>{localStorage.removeItem('flareData');loadForm()};document.getElementById('refreshRates').onclick=refreshRates;setupTabs();if(sessionStorage.getItem('flareAdmin')==='1')showPanel();
