(function(){
  const form=document.getElementById('loginForm');
  const json=async r=>{const t=await r.text();try{return JSON.parse(t)}catch{return {error:t||('HTTP '+r.status)}}};
  const api=async (url,options={})=>fetch(url,{cache:'no-store',credentials:'same-origin',...options});
  async function login(e){e.preventDefault();e.stopImmediatePropagation();const err=document.getElementById('loginError');if(err)err.textContent='Входим…';try{const r=await api('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:document.getElementById('login')?.value||'',password:document.getElementById('password')?.value||''})});const d=await json(r);if(!r.ok||!d.authenticated)throw new Error(d.error||'Не удалось войти');sessionStorage.setItem('flareAdmin','1');if(err)err.textContent='';if(typeof showPanel==='function')showPanel()}catch(x){if(err)err.textContent='❌ '+x.message}}
  if(form)form.addEventListener('submit',login,true);
  const keys=['liveEnabled','vkUrl','onairTitle','onairText','nextTitle','nextTime','newsSource','newsTitle','newsText','newsTime','news2Title','news2Text','news2Category','news3Title','news3Text','news3Category','aboutText','aboutYear','program1Title','program1Text','program2Title','program2Text','program3Title','program3Text','rateUSD','rateEUR','rateGold','rateSilver','ratePlatinum','ratePalladium','rateUpdated'];
  for(let i=1;i<=12;i++)keys.push(`sch${i}Time`,`sch${i}Title`,`sch${i}Category`,`sch${i}Text`,`sch${i}Image`);
  function getScheduleFromHidden(){const raw=document.getElementById('scheduleData')?.value||'';try{const x=JSON.parse(raw);return Array.isArray(x)?x:[]}catch{return []}}
  function putFirstDayIntoHomepage(payload,schedule){const first=Array.isArray(schedule?.[0])?schedule[0]:[];for(let i=0;i<6;i++){const p=first[i]||{};payload[`sch${i+1}Time`]=String(p.time??'');payload[`sch${i+1}Title`]=String(p.title??'');payload[`sch${i+1}Category`]=String(p.category??'');payload[`sch${i+1}Text`]=String(p.description??'');payload[`sch${i+1}Image`]=String(p.image??'')}if(first[0]){payload.onairTitle=String(first[0].title??'');payload.onairText=String(first[0].description??'')}if(first[1]){payload.nextTitle=String(first[1].title??'');payload.nextTime=String(first[1].time??'')}}
  async function saveServerConfig(){const payload={};for(const k of keys){const el=document.getElementById(k);if(el)payload[k]=el.type==='checkbox'?el.checked:el.value}const schedule=getScheduleFromHidden();if(schedule.length){payload.scheduleData=schedule;putFirstDayIntoHomepage(payload,schedule)}const r=await api('/api/schedule?ts='+Date.now(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await json(r);if(!r.ok)throw new Error(d.error||('HTTP '+r.status));localStorage.setItem('flareData',JSON.stringify({...payload,...d}));if(schedule.length)localStorage.setItem('flareScheduleData',JSON.stringify(schedule));return d}
  const save=document.getElementById('save');if(save)save.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();const s=document.getElementById('saved');if(s)s.textContent='⏳ Сохраняем на сервер…';try{await saveServerConfig();if(s)s.textContent='✓ Все изменения сохранены на сервере'}catch(x){if(s)s.textContent='❌ '+x.message}setTimeout(()=>{if(s)s.textContent=''},5000)},true);
  const logout=document.getElementById('logout');if(logout)logout.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();try{await api('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})})}finally{sessionStorage.removeItem('flareAdmin');location.reload()}},true);
  async function refreshServerConfig(){try{const r=await api('/api/schedule?ts='+Date.now());if(!r.ok)return;const d=await r.json();const local=JSON.parse(localStorage.getItem('flareData')||'{}');localStorage.setItem('flareData',JSON.stringify({...local,...d}));for(const [k,v] of Object.entries(d)){const el=document.getElementById(k);if(el){if(el.type==='checkbox')el.checked=!!v;else if(el.tagName==='INPUT'||el.tagName==='TEXTAREA'||el.tagName==='SELECT')el.value=v??''}}if(Array.isArray(d.scheduleData)&&d.scheduleData.length){const hidden=document.getElementById('scheduleData');if(hidden){hidden.value=JSON.stringify(d.scheduleData);localStorage.setItem('flareScheduleData',hidden.value)}window.dispatchEvent(new CustomEvent('flare:schedule-loaded'))}}catch{}}
  async function toggleSite(enabled){const status=document.getElementById('siteStatus');const button=document.getElementById('siteToggle');if(button)button.disabled=true;if(status)status.textContent='⏳ Сохраняем состояние сайта…';try{const payload={enabled:Boolean(enabled),title:'FLARE — сайт временно закрыт',text:'Сайт временно закрыт на обновление или технические работы. Пожалуйста, зайдите позже.',expiresAt:null};const r=await api('/api/site-status?ts='+Date.now(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await json(r);if(!r.ok)throw new Error(d.error||('HTTP '+r.status));if(typeof renderSiteStatus==='function')renderSiteStatus(d.enabled===true);if(status)status.textContent=d.enabled?'✓ Сайт закрыт для посетителей':'✓ Сайт снова доступен';return d}catch(e){if(status)status.textContent='❌ '+e.message;throw e}finally{if(button)button.disabled=false}}
  const siteToggle=document.getElementById('siteToggle');if(siteToggle)siteToggle.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();const currentlyOff=document.getElementById('siteState')?.classList.contains('isOff');try{await toggleSite(!currentlyOff)}catch{}},true);
  if(sessionStorage.getItem('flareAdmin')==='1')setTimeout(refreshServerConfig,250);
})();
