const DEFAULTS={liveEnabled:false,vkUrl:'',onairTitle:'FLARE. Новости',onairText:'Главные события дня — коротко и по делу.',nextTitle:'Истории города',nextTime:'10:25',sch1Time:'10:00',sch1Title:'FLARE. Новости',sch2Time:'10:25',sch2Title:'Истории города',sch3Time:'11:00',sch3Title:'Дайджест',sch4Time:'11:30',sch4Title:'FLARE. Погода',sch5Time:'12:00',sch5Title:'Новости',sch6Time:'12:30',sch6Title:'FLARE. Интервью',newsSource:'telegram',newsTitle:'Главные события дня: что важно знать прямо сейчас',newsText:'Короткие новости, важные события и комментарии редакции FLARE.',newsTime:'СЕГОДНЯ · 10:15',news2Title:'Что изменится этой осенью',news2Text:'Главные изменения и события дня.',news2Category:'Общество',news3Title:'Новые технологии меняют привычный эфир',news3Text:'Главное из мира технологий.',news3Category:'Технологии',aboutText:'FLARE — интернет-телеканал нового формата: новости, программы, прямые трансляции и важные события.',aboutYear:'2026',program1Title:'Дайджест',program1Text:'Самое важное за день',program2Title:'FLARE. Новости',program2Text:'Оперативно и без лишнего',program3Title:'Прямой эфир',program3Text:'События в реальном времени',rateUSD:92.5,rateEUR:107.8,rateGold:10450,rateSilver:145,ratePlatinum:4200,ratePalladium:3800,rateUpdated:''};
const getLocal=()=>{try{return JSON.parse(localStorage.getItem('flareData')||'{}')}catch{return {}}};
function setVal(id,v){const e=document.getElementById(id);if(e)e.type==='checkbox'?e.checked=!!v:e.value=v??''}
function loadForm(d={}){const data={...DEFAULTS,...d,...getLocal()};Object.entries(data).forEach(([k,v])=>setVal(k,v))}
function tabs(){document.querySelectorAll('.adminTab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.adminTab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.adminTabPanel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab)?.classList.add('active')}))}
function showPanel(){document.getElementById('loginBox').hidden=true;document.getElementById('panel').hidden=false;loadServerData();loadSiteStatus();loadUrgent()}
async function login(e){e.preventDefault();const err=document.getElementById('loginError');err.textContent='⏳ Проверяем…';try{const r=await fetch('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({login:document.getElementById('login').value,password:document.getElementById('password').value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка входа');sessionStorage.setItem('flareAdmin','1');err.textContent='';showPanel()}catch(x){err.textContent='❌ '+x.message}}
async function logout(){try{await fetch('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:'logout'})})}catch{}sessionStorage.removeItem('flareAdmin');location.reload()}
async function refreshRates(){const s=document.getElementById('rateStatus');s.textContent='Обновляем…';try{const r=await fetch('https://www.cbr-xml-daily.ru/daily_json.js',{cache:'no-store'});if(!r.ok)throw new Error('Сервис ЦБ недоступен');const j=await r.json();if(j.Valute?.USD?.Value)setVal('rateUSD',Number(j.Valute.USD.Value).toFixed(4));if(j.Valute?.EUR?.Value)setVal('rateEUR',Number(j.Valute.EUR.Value).toFixed(4));s.textContent='✓ USD и EUR обновлены'}catch(e){s.textContent='❌ '+e.message}setTimeout(()=>s.textContent='',4000)}
async function loadServerData(){try{const r=await fetch('/api/schedule?ts='+Date.now(),{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();loadForm(d);if(Array.isArray(d.scheduleData)&&d.scheduleData.length)window.setFlareScheduleData?.(d.scheduleData);document.getElementById('scheduleStatus').textContent='✓ Данные загружены с сервера'}catch(e){loadForm();document.getElementById('scheduleStatus').textContent='⚠️ '+e.message}}
function collect(){const d={};Object.keys(DEFAULTS).forEach(k=>{const e=document.getElementById(k);if(e)d[k]=e.type==='checkbox'?e.checked:e.value});const week=window.getFlareScheduleData?.();if(Array.isArray(week)&&week.length)d.scheduleData=week;return d}
async function save(){const status=document.getElementById('saved');status.textContent='⏳ Сохраняем…';const payload=collect();try{const r=await fetch('/api/schedule?ts='+Date.now(),{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('HTTP '+r.status));localStorage.setItem('flareData',JSON.stringify(d));if(Array.isArray(d.scheduleData))localStorage.setItem('flareScheduleData',JSON.stringify(d.scheduleData));status.textContent='✓ Все изменения сохранены на сервере';const ss=document.getElementById('scheduleStatus');if(ss)ss.textContent='✓ Телепрограмма сохранена на сервере'}catch(e){status.textContent='❌ '+e.message}setTimeout(()=>status.textContent='',5000)}
async function setSiteStatus(enabled){const button=document.getElementById('siteToggle'),s=document.getElementById('siteStatus');if(button)button.disabled=true;if(s)s.textContent='⏳ Сохраняем…';const payload={enabled,title:'FLARE — сайт отключён на обновления или просто отключён.',text:'Сайт закрыт до неопределённого времени. Информация в Telegram.',expiresAt:null};try{const r=await fetch('/api/site-status?ts='+Date.now(),{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(enabled?payload:{...payload,enabled:false})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('HTTP '+r.status));renderSiteStatus(d.enabled===true);if(s)s.textContent=d.enabled?'✓ Сайт отключён':'✓ Сайт включён'}catch(e){if(s)s.textContent='❌ '+e.message}finally{if(button)button.disabled=false}}
function renderSiteStatus(on){const b=document.getElementById('siteToggle'),st=document.getElementById('siteState');if(b)b.textContent=on?'Включить сайт':'Выключить сайт';if(st){st.textContent=on?'Сайт сейчас отключён':'Сайт сейчас включён';st.className='siteState '+(on?'isOff':'isOn')}}
async function loadSiteStatus(){try{const r=await fetch('/api/site-status?ts='+Date.now(),{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();renderSiteStatus(d.enabled===true);const s=document.getElementById('siteStatus');if(s)s.textContent=d.enabled?'Сайт сейчас отключён':'Сайт сейчас включён'}catch(e){renderSiteStatus(false);const s=document.getElementById('siteStatus');if(s)s.textContent='⚠️ '+e.message}}
function addSiteTab(){if(document.getElementById('siteTab'))return;const tabsEl=document.querySelector('.adminTabs');const b=document.createElement('button');b.className='adminTab';b.dataset.tab='siteTab';b.id='siteTabButton';b.textContent='🌐 Сайт';tabsEl.appendChild(b);const p=document.createElement('section');p.id='siteTab';p.className='adminTabPanel';p.innerHTML='<div class="adminGrid"><section class="adminCard wide siteControlCard"><span class="eyebrow">FLARE / SITE</span><h2>Сайт</h2><p class="muted">Управление доступностью сайта.</p><div class="siteControl"><div class="siteState isOn" id="siteState">Сайт сейчас включён</div><button class="redBtn siteToggleBtn" id="siteToggle" type="button">Выключить сайт</button><div id="siteStatus" class="saved"></div></div></section></div>';document.getElementById('panel').appendChild(p);b.addEventListener('click',()=>{document.querySelectorAll('.adminTab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.adminTabPanel').forEach(x=>x.classList.remove('active'));b.classList.add('active');p.classList.add('active');loadSiteStatus()});p.querySelector('#siteToggle').addEventListener('click',()=>setSiteStatus(document.getElementById('siteState').classList.contains('isOn')))}
async function loadUrgent(){try{const r=await fetch('/api/urgent-news?ts='+Date.now(),{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();setVal('urgentEnabled',d.enabled);setVal('urgentTitle',d.title);setVal('urgentText',d.text);const s=document.getElementById('urgentStatus');if(s)s.textContent=d.enabled?'🔴 Срочная новость опубликована':'Срочная новость выключена'}catch(e){const s=document.getElementById('urgentStatus');if(s)s.textContent='❌ '+e.message}}
async function saveUrgent(enabled){const s=document.getElementById('urgentStatus');if(s)s.textContent='⏳ Сохраняем…';try{const r=await fetch('/api/urgent-news?ts='+Date.now(),{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,title:document.getElementById('urgentTitle')?.value||'',text:document.getElementById('urgentText')?.value||''})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('HTTP '+r.status));setVal('urgentEnabled',d.enabled);if(s)s.textContent=d.enabled?'✓ Срочная новость опубликована':'✓ Срочная новость скрыта'}catch(e){if(s)s.textContent='❌ '+e.message}}
addSiteTab();
tabs();
document.getElementById('loginForm')?.addEventListener('submit',login);document.getElementById('logout')?.addEventListener('click',logout);document.getElementById('save')?.addEventListener('click',save);document.getElementById('reset')?.addEventListener('click',()=>{localStorage.removeItem('flareData');loadServerData()});document.getElementById('refreshRates')?.addEventListener('click',refreshRates);document.getElementById('saveUrgent')?.addEventListener('click',()=>saveUrgent(true));document.getElementById('urgentOff')?.addEventListener('click',()=>saveUrgent(false));
if(sessionStorage.getItem('flareAdmin')==='1')showPanel();
