(function(){
  function init(){
    if(document.body.classList.contains('adminPage')||document.getElementById('flareAuthModal'))return;
    const tools=document.querySelector('.navTools');
    if(!tools)return;
    const btn=document.createElement('button');btn.className='authNavBtn';btn.type='button';btn.textContent='Регистрация';tools.insertBefore(btn,tools.firstChild);
    const modal=document.createElement('div');modal.id='flareAuthModal';modal.className='flareAuthModal';modal.innerHTML=`<div class="flareAuthBackdrop"></div><div class="flareAuthCard" role="dialog" aria-modal="true" aria-labelledby="flareAuthTitle"><button class="flareAuthClose" type="button">×</button><span class="flareAuthEyebrow">FLARE / ACCOUNT</span><h2 id="flareAuthTitle">Регистрация</h2><p class="flareAuthSub">Создайте аккаунт на FLARE.Press</p><div class="flareAuthStep" data-step="email"><label>Email<input id="flareAuthEmail" type="email" placeholder="you@example.com" autocomplete="email"></label><button class="authPrimary" id="flareAuthSend" type="button">Получить код</button><button class="authTelegram" id="flareAuthTelegram" type="button">Telegram</button></div><div class="flareAuthStep" data-step="code" hidden><label>Код из письма<input id="flareAuthCode" inputmode="numeric" maxlength="6" placeholder="123456" autocomplete="one-time-code"></label><button class="authPrimary" id="flareAuthVerify" type="button">Подтвердить</button><button class="authBack" id="flareAuthBack" type="button">Изменить email</button></div><div id="flareAuthStatus" class="flareAuthStatus" aria-live="polite"></div></div>`;document.body.appendChild(modal);
    const status=()=>document.getElementById('flareAuthStatus'), email=()=>document.getElementById('flareAuthEmail'), code=()=>document.getElementById('flareAuthCode');
    const open=()=>{modal.classList.add('open');email()?.focus()}; const close=()=>modal.classList.remove('open');btn.onclick=open;modal.querySelector('.flareAuthBackdrop').onclick=close;modal.querySelector('.flareAuthClose').onclick=close;
    document.getElementById('flareAuthTelegram').onclick=()=>{status().textContent='Временно не работает';status().className='flareAuthStatus warn'};
    document.getElementById('flareAuthSend').onclick=async()=>{const e=email().value.trim();status().textContent='Отправляем код…';status().className='flareAuthStatus';try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'register-start',email:e})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка');document.querySelector('[data-step="email"]').hidden=true;document.querySelector('[data-step="code"]').hidden=false;status().textContent='Код отправлен на почту.';code().focus()}catch(x){status().textContent=x.message;status().className='flareAuthStatus error'}};
    document.getElementById('flareAuthVerify').onclick=async()=>{const e=email().value.trim(),c=code().value.trim();status().textContent='Проверяем код…';try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'register-verify',email:e,code:c})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка');status().textContent='✓ Регистрация завершена. Добро пожаловать!';status().className='flareAuthStatus success';setTimeout(close,1200)}catch(x){status().textContent=x.message;status().className='flareAuthStatus error'}};
    document.getElementById('flareAuthBack').onclick=()=>{document.querySelector('[data-step="email"]').hidden=false;document.querySelector('[data-step="code"]').hidden=true;status().textContent=''};
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
