(()=>{
const DAYS=['ВОСКРЕСЕНЬЕ','ПОНЕДЕЛЬНИК','ВТОРНИК','СРЕДА','ЧЕТВЕРГ','ПЯТНИЦА','СУББОТА'];const MONTHS=['ЯНВ','ФЕВ','МАР','АПР','МАЙ','ИЮН','ИЮЛ','АВГ','СЕН','ОКТ','НОЯ','ДЕК'];
const fallback=[['10:00','FLARE. Новости','Новости','Главные события дня, коротко и по делу.',''],['10:25','Истории города','Общество','Люди, места и события города.',''],['11:00','Дайджест','Дайджест','Самое важное за час — без лишнего.',''],['11:30','FLARE. Погода','Погода','Погода в Москве и регионах.',''],['12:00','Новости','Новости','Дневной выпуск новостей FLARE.',''],['12:30','FLARE. Интервью','Интервью','Разговоры с гостями и героями дня.','']];
let data={};let filter='now';let selectedDay=0;let week=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fallbackWeek(){return Array.from({length:7},()=>fallback.map(x=>({time:x[0],title:x[1],category:x[2],description:x[3],image:x[4]})))}
function validWeek(v){return Array.isArray(v)&&v.length>0&&Array.isArray(v[0])}
function card(p,i){const current=i===0&&selectedDay===0&&filter==='now';const later=i>0;return `<article class="programRow ${current?'current':''}${later?' laterProgram':''}"><time>${esc(p.time)}</time><div class="programCover" ${p.image?`style="background-image:url('${esc(p.image)}')"`:''}></div><div class="programInfo"><div class="programMeta">${esc(p.category)}</div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><a class="episodes" href="programs.html">ВСЕ ВЫПУСКИ</a></div></article>`}
function findCurrent(items){if(selectedDay!==0)return items.slice(0,1);const now=new Date();const mins=now.getHours()*60+now.getMinutes();let idx=-1;items.forEach((p,i)=>{const m=/^(\d{1,2}):(\d{2})$/.exec(String(p.time||''));if(m&&Number(m[1])*60+Number(m[2])<=mins)idx=i});return idx>=0?[items[idx]]:(items.length?[items[0]]:[])}
function render(){const list=document.getElementById('scheduleList');if(!list)return;let ps=(week[selectedDay]||[]).filter(p=>p&&(p.time||p.title||p.description||p.image));if(filter==='morning')ps=ps.filter(p=>(p.time||'00:00')<'12:00');if(filter==='evening')ps=ps.filter(p=>(p.time||'00:00')>='17:00');if(filter==='now')ps=findCurrent(ps);list.innerHTML=ps.map(card).join('')||'<div class="scheduleEmpty">На выбранный период программ нет.</div>'}
function dates(){const now=new Date();const today=document.getElementById('todayDate');if(today)today.textContent='';for(let n=1;n<=6;n++){const d=new Date(now);d.setDate(now.getDate()+n);const dow=document.getElementById(`dow${n}`);const dateEl=document.getElementById(`date${n}`);if(dow)dow.textContent=`${DAYS[d.getDay()]},`;if(dateEl)dateEl.textContent=`${String(d.getDate()).padStart(2,'0')} ${MONTHS[d.getMonth()]}`}}
function styleDates(){if(document.getElementById('scheduleDatesFix'))return;const s=document.createElement('style');s.id='scheduleDatesFix';s.textContent=`.scheduleDaysBar{height:58px!important;display:flex!important;align-items:stretch!important}.scheduleDays{display:flex!important;align-items:stretch!important;justify-content:stretch!important;gap:0!important;overflow:hidden!important;flex:1 1 auto!important;min-width:0!important}.scheduleArrow{flex:0 0 34px!important;width:34px!important;min-width:34px!important;height:58px!important;font-size:42px!important;line-height:1!important;padding:0 0 4px!important}.day{min-width:0!important;flex:1 1 0!important;width:0!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:4px!important;padding:0 5px!important;overflow:hidden!important;white-space:nowrap!important;font-size:13px!important;letter-spacing:-.15px!important}.dayLabel,.dayDate{display:inline-block!important;min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.dayDate{font-size:12px!important}.day.active{border-bottom:4px solid #ef1616!important}@media(max-width:1050px){.day{font-size:11.5px!important;padding:0 3px!important}.dayDate{font-size:11px!important}}@media(max-width:760px){.scheduleDaysBar{height:50px!important}.scheduleArrow{flex-basis:28px!important;width:28px!important;min-width:28px!important;height:50px!important;font-size:36px!important}.day{font-size:9px!important;padding:0 2px!important;gap:2px!important}.dayDate{font-size:8.5px!important}}`;document.head.appendChild(s)}
async function load(){try{const r=await fetch('/api/schedule?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(validWeek(d.scheduleData)){data=d;week=d.scheduleData;localStorage.setItem('flareScheduleData',JSON.stringify(week));}else{week=fallbackWeek()}}catch(e){try{const x=JSON.parse(localStorage.getItem('flareScheduleData')||'null');week=validWeek(x)?x:fallbackWeek()}catch{week=fallbackWeek()}}render()}
function selectDay(n){selectedDay=Math.max(0,Math.min(6,n));document.querySelectorAll('.day').forEach(x=>x.classList.remove('active'));const btn=document.querySelector(`.day[data-day="${selectedDay===0?'today':selectedDay}"]`);if(btn)btn.classList.add('active');render()}
document.addEventListener('click',e=>{const day=e.target.closest('.day');if(day){const n=day.dataset.day;if(n==='prev'){selectDay(Math.max(0,selectedDay-1));return}selectDay(n==='today'?0:Number(n)||0);filter='now';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='now'));render()}const arrow=e.target.closest('.scheduleArrow');if(arrow){selectDay(arrow.classList.contains('prev')?Math.max(0,selectedDay-1):Math.min(6,selectedDay+1));filter='now';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='now'));render()}const f=e.target.closest('.filter');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');filter=f.dataset.filter;render()}});
async function init(){styleDates();dates();await load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();setInterval(load,30000);
})();