(()=>{
const DAYS=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'];const MONTHS=['ЯНВ','ФЕВ','МАР','АПР','МАЙ','ИЮН','ИЮЛ','АВГ','СЕН','ОКТ','НОЯ','ДЕК'];
const fallback=[['10:00','FLARE. Новости','Новости','Главные события дня, коротко и по делу.',''],['10:25','Истории города','Общество','Люди, места и события города.',''],['11:00','Дайджест','Дайджест','Самое важное за час — без лишнего.',''],['11:30','FLARE. Погода','Погода','Погода в Москве и регионах.',''],['12:00','Новости','Новости','Дневной выпуск новостей FLARE.',''],['12:30','FLARE. Интервью','Интервью','Разговоры с гостями и героями дня.','']];
let data={};let filter='all';let selectedDay=0;let week=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fallbackWeek(){return Array.from({length:7},()=>fallback.map(x=>({time:x[0],title:x[1],category:x[2],description:x[3],image:x[4]})))}
function validWeek(v){return Array.isArray(v)&&v.length>0&&Array.isArray(v[0])}
function getWeek(){if(validWeek(data.scheduleData))return data.scheduleData;return fallbackWeek()}
function card(p,i){return `<article class="programRow ${i===0&&selectedDay===0?'current':''}"><time>${esc(p.time)}</time><div class="programCover" ${p.image?`style="background-image:url('${esc(p.image)}')"`:''}><span>${esc(p.title)}</span></div><div class="programInfo"><div class="programMeta">${i===0&&selectedDay===0?'<span class="liveBadge">СЕЙЧАС</span>':''}<span>${esc(p.category)}</span></div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p></div><a class="episodes" href="programs.html">Подробнее →</a></article>`}
function render(){const list=document.getElementById('scheduleList');if(!list)return;let ps=(week[selectedDay]||[]).filter(p=>p&&(p.time||p.title||p.description||p.image));if(filter==='morning')ps=ps.filter(p=>(p.time||'00:00')<'12:00');if(filter==='evening')ps=ps.filter(p=>(p.time||'00:00')>='17:00');if(filter==='now')ps=findCurrent(ps);list.innerHTML=ps.map(card).join('')||'<div class="scheduleEmpty">На выбранный период программ нет.</div>'}
function findCurrent(items){if(selectedDay!==0)return items.slice(0,1);const now=new Date();const mins=now.getHours()*60+now.getMinutes();let idx=-1;items.forEach((p,i)=>{const m=/^(\d{1,2}):(\d{2})$/.exec(String(p.time||''));if(m&&Number(m[1])*60+Number(m[2])<=mins)idx=i});return idx>=0?[items[idx]]:(items.length?[items[0]]:[])}
function dates(){const now=new Date();for(let n=0;n<=6;n++){const d=new Date(now);d.setDate(now.getDate()+n);const el=document.getElementById(n===0?'todayDate':`date${n}`);if(el)el.textContent=`${String(d.getDate()).padStart(2,'0')} ${MONTHS[d.getMonth()]}`;if(n>1){const dow=document.getElementById(`dow${n}`);if(dow)dow.textContent=DAYS[d.getDay()]}}}
async function load(){try{const r=await fetch('/api/schedule?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(validWeek(d.scheduleData)){data=d;week=d.scheduleData;localStorage.setItem('flareScheduleData',JSON.stringify(week));}else{week=fallbackWeek()}}catch(e){try{const x=JSON.parse(localStorage.getItem('flareScheduleData')||'null');week=validWeek(x)?x:fallbackWeek()}catch{week=fallbackWeek()}}render()}
document.addEventListener('click',e=>{const day=e.target.closest('.day');if(day){const n=day.dataset.day;if(n==='prev')return;selectedDay=Math.max(0,Math.min(6,Number(n)||0));document.querySelectorAll('.day').forEach(x=>x.classList.remove('active'));day.classList.add('active');filter='all';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));render()}const f=e.target.closest('.filter');if(f){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');filter=f.dataset.filter;render()}});
async function init(){dates();await load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();setInterval(load,30000);
})();