const items=[['Главные события дня: что важно знать прямо сейчас','Новости','news.html'],['Что изменится этой осенью','Общество','news.html'],['Новые технологии меняют привычный эфир','Технологии','news.html'],['FLARE. Новости','Программа','programs.html'],['Истории города','Программа','programs.html'],['Дайджест','Программа','programs.html'],['Телепрограмма FLARE','Эфир','schedule.html']];
let telegramSearchPosts=[];let telegramSearchLoaded=false;let telegramSearchLoading=false;
const DEFAULT_FLARE={liveEnabled:false,vkUrl:'',onairTitle:'FLARE. Новости',onairText:'Главные события дня — коротко и по делу.',newsSource:'telegram',newsTitle:'Главные события дня: что важно знать прямо сейчас',newsText:'Короткие новости, важные события и комментарии редакции FLARE.',newsTime:'СЕГОДНЯ · 10:15',news2Title:'Что изменится этой осенью',news2Text:'Главные изменения и события дня.',news3Title:'Новые технологии меняют привычный эфир',news3Text:'Главное из мира технологий.',aboutText:'FLARE — интернет-телеканал нового формата: новости, программы, прямые трансляции и важные события.',aboutYear:'2026'};
function flareData(){try{return {...DEFAULT_FLARE,...JSON.parse(localStorage.getItem('flareData')||'{}')}}catch{return {...DEFAULT_FLARE}}}
function applyFlareData(){const d=flareData();Object.entries(d).forEach(([k,v])=>{document.querySelectorAll('#'+k).forEach(e=>{if(e.tagName==='INPUT'||e.tagName==='TEXTAREA')e.value=v;else e.textContent=v})});const wrap=document.getElementById('vkPlayerWrap'),iframe=document.getElementById('vkPlayer'),off=document.getElementById('offlineState');if(wrap&&iframe&&off){if(d.liveEnabled&&d.vkUrl){iframe.src=d.vkUrl;wrap.hidden=false;off.hidden=true}else{iframe.removeAttribute('src');wrap.hidden=true;off.hidden=false}}}
async function loadServerSchedule(){try{const r=await fetch('/api/schedule?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();['onairTitle','onairText','sch1Title','sch2Title','sch3Title','sch4Title','sch5Title','sch6Title','nextTitle','nextTime','sch1Time','sch2Time','sch3Time','sch4Time','sch5Time','sch6Time'].forEach(id=>document.querySelectorAll('#'+id).forEach(e=>{if(e.tagName==='INPUT'||e.tagName==='TEXTAREA')e.value=d[id]??e.value;else e.textContent=d[id]??e.textContent}))}catch{}}
async function loadServerConfig(){try{const r=await fetch('/api/schedule?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();localStorage.setItem('flareData',JSON.stringify({...flareData(),...d}));applyFlareData();applyDynamicScheduleAndPrograms();renderFlareRates()}catch{}}
function openSearch(){const s=document.getElementById('search');if(!s)return;s.classList.add('open');const q=document.getElementById('q');if(q){q.value='';searchSite();q.focus()}loadTelegramSearchNews()}
function closeSearch(e){const s=document.getElementById('search');if(!s)return;if(!e||e.target===s)s.classList.remove('open')}
async function loadTelegramSearchNews(){if(telegramSearchLoaded||telegramSearchLoading)return;telegramSearchLoading=true;try{const r=await fetch('/api/telegram?search=1&ts='+Date.now(),{cache:'no-store'});if(r.ok){const d=await r.json();telegramSearchPosts=Array.isArray(d.posts)?d.posts:[];telegramSearchLoaded=true}}catch{}finally{telegramSearchLoading=false;searchSite()}}
function searchSite(){const q=(document.getElementById('q')?.value||'').trim().toLowerCase(),r=document.getElementById('results');if(!r)return;const local=items.filter(x=>!q||x[0].toLowerCase().includes(q)||x[1].toLowerCase().includes(q));let news=telegramSearchPosts.filter(p=>{const title=String(p.title||'').toLowerCase(),body=String(p.body||p.text||'').toLowerCase();return !q||title.includes(q)||body.includes(q)});if(!q)news=[];const html=local.map(x=>`<a class="result" href="${x[2]}"><b>${x[0]}</b><small>${x[1]}</small></a>`).join('')+news.map(p=>{const title=escHtml(p.title||String(p.text||'Публикация FLARE').split(/\n+/)[0]);const id=encodeURIComponent(String(p.id||''));return `<a class="result" href="article.html?id=${id}"><b>${title}</b><small>Новости · FLARE</small></a>`}).join('');r.innerHTML=html||'<p>Ничего не найдено</p>';if(telegramSearchLoading&&!news.length&&q)r.innerHTML='<p>Ищем новости…</p>'}
function updateClock(){const el=document.getElementById('clock');if(el)el.textContent=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'}).format(new Date())}
function renderFlareRates(){const d=flareData();document.querySelectorAll('[data-rate]').forEach(e=>{const v=d['rate'+e.dataset.rate];e.textContent=v?Number(v).toLocaleString('ru-RU',{maximumFractionDigits:4})+' ₽':'—'});document.querySelectorAll('[data-rate-date]').forEach(e=>e.textContent=d.rateUpdated||'Курс в админ-панели')}
const escHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderManualNews(target,d){const cards=[{title:d.newsTitle,text:d.newsText,meta:d.newsTime||'FLARE',cat:'Главное',index:0},{title:d.news2Title,text:d.news2Text,meta:'FLARE',cat:d.news2Category||'Новости',index:1},{title:d.news3Title,text:d.news3Text,meta:'FLARE',cat:d.news3Category||'Новости',index:2}];target.innerHTML=cards.map(p=>`<a class="telegramCard telegramCardClickable" href="article.html?manual=1&index=${p.index}"><div class="telegramCardTop"><span>${escHtml(p.cat)}</span><time>${escHtml(p.meta)}</time></div><h3>${escHtml(p.title)}</h3><p>${escHtml(p.text)}</p><div class="telegramCardBottom"><span>FLARE</span><span class="articleMore">Подробнее →</span></div></a>`).join('')}
function splitTelegramPost(raw){const lines=String(raw||'Медиа-публикация FLARE').split(/\n+/).map(x=>x.trim()).filter(Boolean);return{title:lines[0]||'Публикация FLARE',body:lines.slice(1).join('\n\n')}}
async function loadTelegramNews(){const targets=[document.getElementById('telegramNewsHome'),document.getElementById('telegramNewsPage')].filter(Boolean);if(!targets.length)return;const d=flareData();if(d.newsSource==='manual'){targets.forEach(t=>renderManualNews(t,d));return}const renderEmpty=(message='Пока нет свежих публикаций.')=>targets.forEach(t=>t.innerHTML=`<div class="telegramEmpty">${message} <a href="https://t.me/flare_itv" target="_blank" rel="noopener">Открыть Telegram FLARE →</a></div>`);const renderPosts=posts=>{telegramSearchPosts=posts;telegramSearchLoaded=true;targets.forEach(target=>{if(!posts.length){renderEmpty();return}const limit=target.id==='telegramNewsHome'?3:12;target.innerHTML=posts.slice(0,limit).map(p=>{const parsed=splitTelegramPost(p.title||p.text);const title=escHtml(parsed.title);const body=escHtml(parsed.body);const date=p.time?new Date(p.time).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'';const id=encodeURIComponent(String(p.id||''));const image=p.image?`<img class="telegramImage" src="${escHtml(p.image)}" alt="" loading="lazy">`:'';const video=p.hasVideo?'<span class="articleMore">▶ Смотреть видео</span>':'<span class="articleMore">Подробнее →</span>';return `<a class="telegramCard telegramCardClickable" href="article.html?id=${id}">${image}<div class="telegramCardTop"><span>FLARE · TELEGRAM</span><time>${date}</time></div><h3>${title}</h3>${body?`<p>${body}</p>`:''}<div class="telegramCardBottom"><span>FLARE</span>${video}</div></a>`}).join('')})};try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);const r=await fetch('/api/telegram?ts='+Date.now(),{cache:'no-store',signal:controller.signal});clearTimeout(timer);if(!r.ok)throw new Error('API HTTP '+r.status);const data=await r.json();renderPosts(Array.isArray(data.posts)?data.posts:[])}catch(e){try{const res=await fetch('data/telegram.json?ts='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error('fallback');const data=await res.json();renderPosts(Array.isArray(data.posts)?data.posts:[])}catch(_){renderEmpty('Лента Telegram временно недоступна.')}}}
function applyDynamicScheduleAndPrograms(){const d=flareData();['onairTitle','onairText','sch1Title','sch2Title','sch3Title','sch4Title','sch5Title','sch6Title','nextTitle','nextTime','program1Title','program1Text','program2Title','program2Text','program3Title','program3Text'].forEach(id=>document.querySelectorAll('#'+id).forEach(e=>e.textContent=d[id]??e.textContent))}
async function loadUrgentBanner(){try{const r=await fetch('/api/urgent-news?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();let el=document.getElementById('urgentBanner');if(!d.enabled){if(el)el.remove();return}if(!el){el=document.createElement('div');el.id='urgentBanner';el.className='urgentBanner';document.body.prepend(el)}el.innerHTML=`<div class="urgentInner"><span class="urgentBadge">🔴 СРОЧНО</span><strong>${escHtml(d.title||'Срочная новость')}</strong><span>${escHtml(d.text||'')}</span></div>`}catch{}}
applyFlareData();updateClock();setInterval(updateClock,1000);document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('search')?.classList.remove('open')});renderFlareRates();applyDynamicScheduleAndPrograms();loadServerConfig();loadServerSchedule();loadTelegramNews();loadUrgentBanner();setInterval(loadServerSchedule,60000);setInterval(loadUrgentBanner,30000);setInterval(()=>{telegramSearchLoaded=false;loadTelegramNews()},60000);
(function(){if(document.body?.classList.contains('adminPage'))return;const addCss=()=>{};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addCss,{once:true})})();
(function(){if(document.body?.classList.contains('adminPage'))return;const addCss=()=>{if(!document.querySelector('link[href="nav-menu.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='nav-menu.css';document.head.appendChild(l)}};const load=()=>{if(window.__flareNavMenuLoaded)return;window.__flareNavMenuLoaded=true;const s=document.createElement('script');s.src='nav-menu.js';s.async=true;document.body.appendChild(s)};addCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();
