import { randomInt, randomBytes, createHash } from 'node:crypto';

const REDIS_URL = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_ENDPOINT;
const REDIS_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN;
const RESEND_KEY = process.env.RESEND_API_KEY;
const FROM_EMAIL = process.env.FLARE_FROM_EMAIL || process.env.RESEND_FROM || 'FLARE <onboarding@resend.dev>';
const SESSION_COOKIE='flare_user';
const CODE_TTL=600;

const redis=async(command,args=[])=>{if(!REDIS_URL||!REDIS_TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(REDIS_URL,{method:'POST',headers:{Authorization:`Bearer ${REDIS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args])});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||`Redis HTTP ${r.status}`);return j.result};
const hash=s=>createHash('sha256').update(String(s)).digest('hex');
const cleanEmail=s=>String(s||'').trim().toLowerCase();
const validEmail=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
function cors(res){res.setHeader('Access-Control-Allow-Origin','same-origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Cache-Control','no-store');return res}
async function sendCode(email,code){if(!RESEND_KEY)throw new Error('Email service is not configured. Add RESEND_API_KEY and FLARE_FROM_EMAIL in Vercel.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${RESEND_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM_EMAIL,to:[email],subject:'Код регистрации FLARE',html:`<div style="font-family:Arial,sans-serif;line-height:1.5"><h2>Регистрация в FLARE</h2><p>Ваш код подтверждения:</p><div style="font-size:32px;font-weight:800;letter-spacing:8px">${code}</div><p>Код действует 10 минут.</p></div>`})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Email HTTP ${r.status}`);return j}
function setSession(res,email){const token=`${email}.${randomBytes(24).toString('hex')}`;res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax`);}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const action=String(body.action||'');if(action==='register-start'){const email=cleanEmail(body.email);if(!validEmail(email))return res.status(400).json({error:'Введите корректный email.'});const code=String(randomInt(100000,1000000));const key=`flare:auth:code:${hash(email)}`;const existing=await redis('GET',[`flare:auth:user:${hash(email)}`]);if(existing)return res.status(409).json({error:'Пользователь с таким email уже зарегистрирован.'});await redis('SET',[key,JSON.stringify({codeHash:hash(code),email,createdAt:Date.now()} ,'EX',CODE_TTL]);await sendCode(email,code);return res.status(200).json({ok:true,message:'Код отправлен на почту.'});}
if(action==='register-verify'){const email=cleanEmail(body.email),code=String(body.code||'').trim();if(!validEmail(email)||!/^[0-9]{6}$/.test(code))return res.status(400).json({error:'Введите email и 6-значный код.'});const key=`flare:auth:code:${hash(email)}`;const raw=await redis('GET',[key]);if(!raw)return res.status(400).json({error:'Код истёк. Запросите новый.'});const saved=JSON.parse(raw);if(saved.codeHash!==hash(code))return res.status(400).json({error:'Неверный код.'});await redis('DEL',[key]);const user={email,createdAt:Date.now(),provider:'email'};await redis('SET',[`flare:auth:user:${hash(email)}`,JSON.stringify(user)]);setSession(res,email);return res.status(200).json({ok:true,user});}
if(action==='telegram-unavailable')return res.status(200).json({ok:false,message:'Временно не работает'});
return res.status(400).json({error:'Неизвестное действие.'});}catch(e){console.error('auth error',e);return res.status(503).json({error:e.message||'Ошибка сервера'});}}
