import { isAdminRequest } from './admin-auth.js';
const KEY='flare:promo-slides';
const REDIS_URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT;
const REDIS_TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;
const DEFAULT_SLIDES=[{title:'ГЛАВНЫЕ НОВОСТИ ВСЕГДА ПОД РУКОЙ',text:'Подписывайтесь на наш канал в Телеграм',button:'Подробнее',link:'https://t.me/flare_itv',image:''},{title:'СОТРУДНИЧАЙТЕ С FLARE',text:'Реклама, сотрудничество и ваши новости — пишите менеджеру.',button:'Подробнее',link:'https://t.me/managerflareof',image:''}];
function headers(res){if(res.headersSent)return;res.setHeader('Access-Control-Allow-Origin','same-origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Cache-Control','no-store')}
function reply(res,status,body){if(res.headersSent)return;headers(res);return res.status(status).json(body)}
async function redis(command,args=[]){if(!REDIS_URL||!REDIS_TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(REDIS_URL,{method:'POST',headers:{Authorization:`Bearer ${REDIS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args]),cache:'no-store'});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
function normalizeSlide(s){return {title:String(s?.title||'').trim(),text:String(s?.text||'').trim(),button:String(s?.button||'Подробнее').trim(),link:String(s?.link||'https://t.me/managerflareof').trim(),image:String(s?.image||'').trim()}}
function normalizeSlides(v){const a=Array.isArray(v)?v:[];return a.map(normalizeSlide).filter(s=>s.title||s.text||s.image)}
export default async function handler(req,res){headers(res);try{if(req.method==='OPTIONS')return res.status(204).end();const raw=await redis('GET',[KEY]);if(req.method==='GET'){let saved=[];if(raw){try{saved=JSON.parse(raw)}catch{saved=[]}}return reply(res,200,{slides:normalizeSlides(saved).length?normalizeSlides(saved):DEFAULT_SLIDES})}if(req.method!=='POST')return reply(res,405,{error:'Method not allowed'});if(!isAdminRequest(req))return reply(res,401,{error:'Unauthorized'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const slides=normalizeSlides(body.slides);if(!slides.length)return reply(res,400,{error:'Добавьте хотя бы один слайд'});await redis('SET',[KEY,JSON.stringify(slides)]);return reply(res,200,{ok:true,slides})}catch(e){console.error('promo-slides error:',e);return reply(res,503,{error:e.message||'Server error'})}}
