import { isAdminRequest } from './admin-auth.js';
const KEY='flare:schedule';
const LOGIN=process.env.FLARE_WORKER_LOGIN||'flareworker';
const PASSWORD=process.env.FLARE_WORKER_PASSWORD||'flareworker';
const REDIS_URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT;
const REDIS_TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;
async function redis(command,args=[]){if(!REDIS_URL||!REDIS_TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(REDIS_URL,{method:'POST',headers:{Authorization:`Bearer ${REDIS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args])});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
const defaults={liveEnabled:false,vkUrl:'',onairTitle:'FLARE. Новости',onairText:'Главные события дня — коротко и по делу.',nextTitle:'Истории города',nextTime:'10:25',sch1Time:'10:00',sch1Title:'FLARE. Новости',sch1Category:'Новости',sch1Text:'Главные события дня, коротко и по делу.',sch2Time:'10:25',sch2Title:'Истории города',sch2Category:'Общество',sch2Text:'Люди, места и события города.',sch3Time:'11:00',sch3Title:'Дайджест',sch3Category:'Дайджест',sch3Text:'Самое важное за час.',sch4Time:'11:30',sch4Title:'FLARE. Погода',sch4Category:'Погода',sch4Text:'Погода в Москве и регионах.',sch5Time:'12:00',sch5Title:'Новости',sch5Category:'Новости',sch5Text:'Дневной выпуск FLARE.',sch6Time:'12:30',sch6Title:'FLARE. Интервью',sch6Category:'Интервью',sch6Text:'Разговоры с гостями и героями дня.',newsSource:'telegram',newsTitle:'Главные события дня: что важно знать прямо сейчас',newsText:'Короткие новости, важные события и комментарии редакции FLARE.',newsTime:'СЕГОДНЯ · 10:15',news2Title:'Что изменится этой осенью',news2Text:'Главные изменения и события дня.',news2Category:'Общество',news3Title:'Новые технологии меняют привычный эфир',news3Text:'Главное из мира технологий.',news3Category:'Технологии',aboutText:'FLARE — интернет-телеканал нового формата: новости, программы, прямые трансляции и важные события.',aboutYear:'2026',program1Title:'Дайджест',program1Text:'Самое важное за день',program2Title:'FLARE. Новости',program2Text:'Оперативно и без лишнего',program3Title:'Прямой эфир',program3Text:'События в реальном времени',rateUSD:92.5,rateEUR:107.8,rateGold:10450,rateSilver:145,ratePlatinum:4200,ratePalladium:3800,rateUpdated:''};
function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-FLARE-Worker-Login, X-FLARE-Worker-Password');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Cache-Control','no-store');return res}
function authorized(req){return isAdminRequest(req)||(req.headers['x-flare-worker-login']===LOGIN&&req.headers['x-flare-worker-password']===PASSWORD)}
export default async function handler(req,res){try{if(req.method==='OPTIONS')return cors(res.status(204)).end();const raw=await redis('GET',[KEY]);if(req.method==='GET'){return cors(res.status(200).json(raw?{...defaults,...JSON.parse(raw)}:defaults))}if(req.method==='POST'){if(!authorized(req))return cors(res.status(401).json({error:'Unauthorized'}));const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const old=raw?JSON.parse(raw):{};const d={...defaults,...old};for(const k of Object.keys(defaults)){if(Object.prototype.hasOwnProperty.call(b,k))d[k]=k==='liveEnabled'?Boolean(b[k]):(typeof defaults[k]==='number'?Number(b[k]):String(b[k]??''))}await redis('SET',[KEY,JSON.stringify(d)]);return cors(res.status(200).json({ok:true,...d}))}return cors(res.status(405).json({error:'Method not allowed'}))}catch(e){console.error(e);return cors(res.status(503).json({error:e.message||'Server error'}))}}
