import { isAdminRequest } from './admin-auth.js';

const KEY='flare:site-config';
const REDIS_URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT;
const REDIS_TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;
const KEYS=['liveEnabled','vkUrl','onairTitle','onairText','nextTitle','nextTime','sch1Time','sch1Title','sch1Category','sch1Text','sch2Time','sch2Title','sch2Category','sch2Text','sch3Time','sch3Title','sch3Category','sch3Text','sch4Time','sch4Title','sch4Category','sch4Text','sch5Time','sch5Title','sch5Category','sch5Text','sch6Time','sch6Title','sch6Category','sch6Text','newsSource','newsTitle','newsText','newsTime','news2Title','news2Text','news2Category','news3Title','news3Text','news3Category','aboutText','aboutYear','program1Title','program1Text','program2Title','program2Text','program3Title','program3Text','rateUSD','rateEUR','rateGold','rateSilver','ratePlatinum','ratePalladium','rateUpdated'];
const defaults={liveEnabled:false,vkUrl:'',onairTitle:'FLARE. Новости',onairText:'Главные события дня — коротко и по делу.',nextTitle:'Истории города',nextTime:'10:25',sch1Time:'10:00',sch1Title:'FLARE. Новости',sch1Category:'Новости',sch1Text:'Главные события дня, коротко и по делу.',sch2Time:'10:25',sch2Title:'Истории города',sch2Category:'Общество',sch2Text:'Люди, места и события города.',sch3Time:'11:00',sch3Title:'Дайджест',sch3Category:'Дайджест',sch3Text:'Самое важное за час.',sch4Time:'11:30',sch4Title:'FLARE. Погода',sch4Category:'Погода',sch4Text:'Погода в Москве и регионах.',sch5Time:'12:00',sch5Title:'Новости',sch5Category:'Новости',sch5Text:'Дневной выпуск FLARE.',sch6Time:'12:30',sch6Title:'FLARE. Интервью',sch6Category:'Интервью',sch6Text:'Разговоры с гостями и героями дня.',newsSource:'telegram',newsTitle:'Главные события дня: что важно знать прямо сейчас',newsText:'Короткие новости, важные события и комментарии редакции FLARE.',newsTime:'СЕГОДНЯ · 10:15',news2Title:'Что изменится этой осенью',news2Text:'Главные изменения и события дня.',news2Category:'Общество',news3Title:'Новые технологии меняют привычный эфир',news3Text:'Главное из мира технологий.',news3Category:'Технологии',aboutText:'FLARE — интернет-телеканал нового формата: новости, программы, прямые трансляции и важные события.',aboutYear:'2026',program1Title:'Дайджест',program1Text:'Самое важное за день',program2Title:'FLARE. Новости',program2Text:'Оперативно и без лишнего',program3Title:'Прямой эфир',program3Text:'События в реальном времени',rateUSD:92.5,rateEUR:107.8,rateGold:10450,rateSilver:145,ratePlatinum:4200,ratePalladium:3800,rateUpdated:''};
function cors(res){res.setHeader('Access-Control-Allow-Origin','same-origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Cache-Control','no-store');return res}
async function redis(command,args=[]){if(!REDIS_URL||!REDIS_TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(REDIS_URL,{method:'POST',headers:{Authorization:`Bearer ${REDIS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args])});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
export default async function handler(req,res){cors(res);try{if(req.method==='OPTIONS')return res.status(204).end();const raw=await redis('GET',[KEY]);if(req.method==='GET'){return res.status(200).json(raw?{...defaults,...JSON.parse(raw)}:defaults)}if(req.method==='POST'){if(!isAdminRequest(req))return res.status(401).json({error:'Unauthorized'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const current=raw?JSON.parse(raw):{};const next={...defaults,...current};for(const key of KEYS){if(Object.prototype.hasOwnProperty.call(body,key))next[key]=key==='liveEnabled'?Boolean(body[key]):String(body[key]??'')}await redis('SET',[KEY,JSON.stringify(next)]);return res.status(200).json({ok:true,...next})}return res.status(405).json({error:'Method not allowed'})}catch(e){console.error('site-config:',e);return res.status(503).json({error:e.message||'Server error'})}}
