import { isAdminRequest } from './admin-auth.js';
const KEY='flare:site-status';
const REDIS_URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT;
const REDIS_TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;
const defaultData={enabled:false,title:'FLARE — сайт отключён на проведение работ',text:'Сайт временно закрыт. Информация в Telegram.',expiresAt:null};
function headers(res){if(res.headersSent)return;res.setHeader('Access-Control-Allow-Origin','same-origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Cache-Control','no-store')}
function reply(res,status,body){if(res.headersSent)return;headers(res);return res.status(status).json(body)}
async function redis(command,args=[]){if(!REDIS_URL||!REDIS_TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(REDIS_URL,{method:'POST',headers:{Authorization:`Bearer ${REDIS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args]),cache:'no-store'});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
function normalize(v){const d={...defaultData,...(v||{})};const expiresAt=d.expiresAt||null;const ms=expiresAt?Date.parse(expiresAt):NaN;const expired=Number.isFinite(ms)&&Date.now()>=ms;return {enabled:Boolean(d.enabled)&&!expired,title:String(d.title||defaultData.title),text:String(d.text||defaultData.text),expiresAt}}
export default async function handler(req,res){headers(res);try{if(req.method==='OPTIONS')return res.status(204).end();if(req.method==='GET'){const raw=await redis('GET',[KEY]);let saved=defaultData;if(raw){try{saved=JSON.parse(raw)}catch{saved=defaultData}}return reply(res,200,normalize(saved))}if(req.method!=='POST')return reply(res,405,{error:'Method not allowed'});if(!isAdminRequest(req))return reply(res,401,{error:'Unauthorized'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const data=normalize({enabled:Boolean(body.enabled),title:body.title,text:body.text,expiresAt:body.expiresAt??null});await redis('SET',[KEY,JSON.stringify(data)]);return reply(res,200,{ok:true,...data})}catch(e){console.error('site-status error:',e);return reply(res,503,{error:e.message||'Server error'})}}
