const CHANNEL='@flare_itv';
const REDIS_KEY='flare:telegram_posts';
const BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN||process.env.TELEGRAM_TOKEN||process.env.BOT_TOKEN||'';
const REDIS_URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT||'';
const REDIS_TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN||'';
const WEBHOOK_URL=process.env.TELEGRAM_WEBHOOK_URL||'https://flare-press.vercel.app/api/telegram';
function decodeHtml(v){return String(v||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/&#33;/g,'!').replace(/&nbsp;/g,' ')}
function normalizeText(v){return typeof v==='string'?v.trim():String(v?.text||'').trim()}
function normalizeBotMessage(m){if(!m)return null;const text=normalizeText(m.text??m.caption),id=String(m.message_id||'');if(!id)return null;const lines=text.split(/\r?\n+/).map(x=>x.replace(/[ \t]+/g,' ').trim()).filter(Boolean);const doc=m.document||null;return{id,text,title:(lines[0]||'Публикация FLARE').slice(0,160),body:lines.slice(1).join('\n\n').trim(),time:m.date?new Date(m.date*1000).toISOString():new Date().toISOString(),link:`https://t.me/flare_itv/${id}`,image:'',videoFileId:m.video?.file_id||(((doc?.mime_type)||'').startsWith('video/')?doc.file_id||'':''),hasVideo:!!m.video||(((doc?.mime_type)||'').startsWith('video/')),source:'telegram-bot'}}
async function redis(command,...args){if(!REDIS_URL||!REDIS_TOKEN)return null;const r=await fetch(`${REDIS_URL}/${command}/${args.map(v=>encodeURIComponent(v)).join('/')}`,{headers:{Authorization:`Bearer ${REDIS_TOKEN}`},cache:'no-store'});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);return r.json()}
async function readPosts(){const r=await redis('get',REDIS_KEY);if(!r?.result)return[];try{return JSON.parse(r.result)}catch{return[]}}
async function writePosts(posts){const clean=posts.filter(Boolean).slice(0,50);if(REDIS_URL&&REDIS_TOKEN)await redis('set',REDIS_KEY,JSON.stringify(clean));return clean}
async function telegram(method,body={}){if(!BOT_TOKEN)throw new Error('Telegram bot token is not configured');const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!d.ok)throw new Error(d.description||`Telegram API error ${r.status}`);return d.result}
async function publicFeed(){const r=await fetch('https://t.me/s/flare_itv',{headers:{'User-Agent':'Mozilla/5.0 FLARE News Reader'},cache:'no-store'});if(!r.ok)throw new Error(`Telegram public HTTP ${r.status}`);const html=await r.text();const out=[];for(const block of html.split('tgme_widget_message_wrap').slice(1).slice(-30)){const idm=block.match(/data-post="flare_itv\/(\d+)"/);if(!idm)continue;const id=idm[1];const tm=block.match(/<div class="tgme_widget_message_text[^>]*>([\s\S]*?)<\/div>/);const text=tm?decodeHtml(tm[1].replace(/<br\s*\/?>(?=.)/gi,'\n').replace(/<[^>]+>/g,'')):'Публикация FLARE';const lines=text.split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);const time=block.match(/<time[^>]+datetime="([^"]+)"/);const photo=block.match(/background-image:url\('([^']+)'\)/);out.push({id,text,title:(lines[0]||'Публикация FLARE').slice(0,160),body:lines.slice(1).join('\n\n'),time:time?.[1]||'',link:`https://t.me/flare_itv/${id}`,image:photo?decodeHtml(photo[1]):'',hasVideo:/tgme_widget_message_video|<video\b/i.test(block),videoUrl:'',source:'telegram-public'})}return out.sort((a,b)=>Number(a.id)-Number(b.id))}
async function ensureWebhook(){if(!BOT_TOKEN)return{configured:false,reason:'bot-token-missing'};try{const info=await telegram('getWebhookInfo');const expected=WEBHOOK_URL; if(info?.url!==expected){const body={url:expected,allowed_updates:['channel_post','edited_channel_post']};const secret=process.env.TELEGRAM_WEBHOOK_SECRET;if(secret)body.secret_token=secret;await telegram('setWebhook',body);return{configured:true,changed:true,url:expected,pending_updates:info?.pending_update_count||0}}return{configured:true,changed:false,url:expected,pending_updates:info?.pending_update_count||0}}catch(e){return{configured:false,error:e.message}}}
async function mergeFresh(){const stored=await readPosts();let fresh=[];try{fresh=await publicFeed()}catch(e){return{posts:stored,source:'redis-fallback',error:e.message,freshOk:false}}const map=new Map();for(const p of [...stored,...fresh]){if(p?.id)map.set(String(p.id),p)}const merged=[...map.values()].sort((a,b)=>{const ta=Date.parse(a.time||'')||0,tb=Date.parse(b.time||'')||0;return tb-ta});const saved=await writePosts(merged);return{posts:saved,source:stored.length?'telegram-public+redis':'telegram-public',freshOk:true,freshCount:fresh.length}}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();try{if(req.method==='POST'){const secret=process.env.TELEGRAM_WEBHOOK_SECRET||'';if(secret&&req.headers['x-telegram-bot-api-secret-token']!==secret)return res.status(401).json({error:'Unauthorized'});const update=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const message=update.channel_post||update.edited_channel_post;if(message)await writePosts([normalizeBotMessage(message),...(await readPosts())]);return res.status(200).json({ok:true,received:!!message})}if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const refresh=String(req.query?.refresh||'')==='1';const result=await mergeFresh();if(refresh&&BOT_TOKEN)result.webhook=await ensureWebhook();return res.status(200).json({posts:result.posts.slice(0,12),source:result.source,freshOk:result.freshOk,freshCount:result.freshCount||0,channel:CHANNEL,bot:'@flare_itv_bot',webhook:result.webhook||{configured:!!BOT_TOKEN,reason:BOT_TOKEN?'manual-refresh-required':'bot-token-missing'},updatedAt:new Date().toISOString()})}catch(e){console.error('Telegram feed error:',e);return res.status(502).json({error:'Telegram feed unavailable',message:String(e.message||e),botConfigured:!!BOT_TOKEN})}}