import { isAdminRequest } from './admin-auth.js';
const KEY='flare:urgent-news';
const URL=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_ENDPOINT;
const TOKEN=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;
const empty={enabled:false,title:'',text:''};
function headers(res){if(res.headersSent)return;res.setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Origin','same-origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS')}
function reply(res,status,body){if(res.headersSent)return;headers(res);return res.status(status).json(body)}
async function redis(command,args=[]){if(!URL||!TOKEN)throw new Error('Upstash Redis is not connected');const r=await fetch(URL,{method:'POST',headers:{Authorization:`Bearer ${TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify([command,...args]),cache:'no-store'});if(!r.ok)throw new Error(`Redis HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error);return j.result}
export default async function handler(req,res){headers(res);try{if(req.method==='OPTIONS')return res.status(204).end();if(req.method==='GET'){const raw=await redis('GET',[KEY]);let data=empty;if(raw){try{data=JSON.parse(raw)}catch{data=empty}}return reply(res,200,{enabled:Boolean(data.enabled),title:String(data.title||''),text:String(data.text||'')})}if(!isAdminRequest(req))return reply(res,401,{error:'Unauthorized'});if(req.method==='DELETE'){await redis('DEL',[KEY]);return reply(res,200,empty)}if(req.method==='POST'){const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const data={enabled:Boolean(b.enabled),title:String(b.title||''),text:String(b.text||'')};await redis('SET',[KEY,JSON.stringify(data)]);return reply(res,200,data)}return reply(res,405,{error:'Method not allowed'})}catch(e){console.error('urgent-news error:',e);return reply(res,503,{error:e.message||'Server error'})}}
